services:
  prometheus:
    build: prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=14d'

  grafana:
    build: grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  prometheus_data: