global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'wtah-monitoring'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ '84.235.166.193:8080' ]
        labels:
          application: 'warm tea and honest api server'